version: "3"
services:
  api:
    container_name: api
    restart: always
    build: ./backend
    ports:
      - "4000:4000"
    depends_on:
      - mongo
  client:
    container_name: app
    restart: always
    build: ./client
    ports:
      - "3000:3000"
    links:
      - api
  mongo:
    container_name: mongo
    image: mongo
    restart: always
    expose:
      - "27017"
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
volumes:
  mongodata: